// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejiav_T7gtv8GvxAYH6KEcFwb7R24HE8',
    appId: '1:503423315901:web:34b73ee98fdaff6ca2acd4',
    messagingSenderId: '503423315901',
    projectId: 'orin-86d35',
    authDomain: 'orin-86d35.firebaseapp.com',
    storageBucket: 'orin-86d35.firebasestorage.app',
    measurementId: 'G-89RYZS9B31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6e7KMeVLHHQrCwiaBVHquH9AN5YXtdE8',
    appId: '1:503423315901:android:7a80e890c03e4fada2acd4',
    messagingSenderId: '503423315901',
    projectId: 'orin-86d35',
    storageBucket: 'orin-86d35.firebasestorage.app',
  );
}
